# ETL Exploration
Use this notebook to prototype and test your ETL pipeline before moving code to `etl/etl.py`.

In [1]:
import pandas as pd
import numpy as np
import os
from dotenv import load_dotenv

load_dotenv()
SIMFIN_API_KEY = os.getenv('SIMFIN_API_KEY')
print('API key loaded:', bool(SIMFIN_API_KEY))

API key loaded: True

## 1. Fetch raw data
TODO: call PySimFin or simfin library here.

In [ ]:
# TODO
df = pd.read_csv('../data/raw/us-shareprices-daily.csv', sep=';')

In [5]:
AAPL = df[df['Ticker'] == 'AAPL']
AAPL.head()

,Ticker,SimFinId,Date,Open,High,Low,Close,Adj. Close,Volume,Dividend,Shares Outstanding
16031,AAPL,111052,2020-04-06,62.73,65.78,62.34,65.62,63.43,201820284,NaN,1.729595e+10
16032,AAPL,111052,2020-04-07,67.70,67.92,64.75,64.86,62.69,202887324,NaN,1.729595e+10
16033,AAPL,111052,2020-04-08,65.69,66.84,65.31,66.52,64.30,168895284,NaN,1.729595e+10
16034,AAPL,111052,2020-04-09,67.17,67.52,66.17,67.00,64.76,162116492,NaN,1.729595e+10
16035,AAPL,111052,2020-04-13,67.08,68.42,66.46,68.31,66.03,131022924,NaN,1.729595e+10

In [6]:
PLTR = df[df['Ticker'] == 'PLTR']
PLTR.head()

,Ticker,SimFinId,Date,Open,High,Low,Close,Adj. Close,Volume,Dividend,Shares Outstanding
4370752,PLTR,1039027,2020-09-30,10.00,11.42,9.11,9.50,9.50,338584433,NaN,1.726686e+09
4370753,PLTR,1039027,2020-10-01,9.69,10.10,9.23,9.46,9.46,124297587,NaN,1.726686e+09
4370754,PLTR,1039027,2020-10-02,9.06,9.28,8.94,9.20,9.20,55018343,NaN,1.726686e+09
4370755,PLTR,1039027,2020-10-05,9.43,9.49,8.92,9.03,9.03,36316878,NaN,1.726686e+09
4370756,PLTR,1039027,2020-10-06,9.04,10.18,8.90,9.90,9.90,90864039,NaN,1.726686e+09

In [ ]:
GOOG = df[df['Ticker'] == 'GOOG']
GOOG.head()

,Ticker,SimFinId,Date,Open,High,Low,Close,Adj. Close,Volume,Dividend,Shares Outstanding
2439130,GOOG,18,2020-04-06,56.90,59.73,56.55,59.35,58.90,53294460,NaN,1.367944e+10
2439131,GOOG,18,2020-04-07,61.05,61.25,59.11,59.33,58.88,47746580,NaN,1.367944e+10
2439132,GOOG,18,2020-04-08,60.33,60.95,59.41,60.51,60.06,39502700,NaN,1.367944e+10
2439133,GOOG,18,2020-04-09,61.20,61.28,59.84,60.57,60.12,43508420,NaN,1.367944e+10
2439134,GOOG,18,2020-04-13,60.46,61.03,59.38,60.88,60.42,34796560,NaN,1.367944e+10

In [9]:
AMZN = df[df['Ticker'] == 'AMZN']
AMZN.head()

,Ticker,SimFinId,Date,Open,High,Low,Close,Adj. Close,Volume,Dividend,Shares Outstanding
335975,AMZN,62747,2020-04-06,96.80,99.93,96.50,99.88,99.88,115463620,NaN,9.980000e+09
335976,AMZN,62747,2020-04-07,100.86,101.79,99.88,100.58,100.58,102279660,NaN,9.980000e+09
335977,AMZN,62747,2020-04-08,101.05,102.20,100.56,102.15,102.15,79546260,NaN,9.980000e+09
335978,AMZN,62747,2020-04-09,102.22,102.65,100.88,102.14,102.14,93112340,NaN,9.980000e+09
335979,AMZN,62747,2020-04-13,102.00,109.00,101.90,108.44,108.44,134334180,NaN,9.980000e+09

In [10]:
MSFT = df[df['Ticker'] == 'MSFT']
MSFT.head()

,Ticker,SimFinId,Date,Open,High,Low,Close,Adj. Close,Volume,Dividend,Shares Outstanding
3692459,MSFT,59265,2020-04-06,160.32,166.50,157.58,165.27,156.98,67111697,NaN,7.590000e+09
3692460,MSFT,59265,2020-04-07,169.59,170.00,163.26,163.49,155.29,62769038,NaN,7.590000e+09
3692461,MSFT,59265,2020-04-08,165.67,166.67,163.50,165.13,156.85,48318234,NaN,7.590000e+09
3692462,MSFT,59265,2020-04-09,166.36,167.37,163.33,165.14,156.85,51431775,NaN,7.590000e+09
3692463,MSFT,59265,2020-04-13,164.35,165.57,162.30,165.51,157.21,41905264,NaN,7.590000e+09

## 2. Clean & explore
Check for nulls, data types, date ranges.

In [ ]:
# TODO

## 3. Feature engineering
Create the derived columns the model will use.

In [ ]:
# TODO